#!/bin/bash

# Function to display information about a subdomain
display_info() {
    sub_domain="$1"
    domain="$2"

    # Query DNS records for the subdomain
    dns_info=$(dig "$sub_domain.$domain" +short)

    # Check if the DNS query returned any result
    if [ -n "$dns_info" ]; then
        echo "The subdomain $sub_domain is a $(dig "$sub_domain.$domain" | awk '/IN\sA/ {print $4}' | head -n1) record and points to $dns_info"
    else
        echo "No information found for the subdomain $sub_domain"
    fi
}

# Function to display information for default subdomains
display_default_subdomains() {
    domain="$1"
    sub_domains=("www" "lb-01" "web-01" "web-02")

    for sub_domain in "${sub_domains[@]}"; do
        display_info "$sub_domain" "$domain"
    done
}

# Main function
main() {
    # Check if the required arguments are provided
    if [ $# -lt 1 ]; then
        echo "Usage: $0 <domain> [<subdomain>]"
        exit 1
    fi

    domain="$1"
    sub_domain="$2"

    # Display information for default subdomains if no specific subdomain is provided
    if [ -z "$sub_domain" ]; then
        display_default_subdomains "$domain"
    else
        display_info "$sub_domain" "$domain"
    fi
}

# Execute the main function with provided arguments
main "$@"

