#!/usr/bin/env bash
# This script displays information about subdomains for a given domain.

# Function to display information about a specific subdomain
display_subdomain_info() {
    sub_domain="$1"
    domain="$2"
    record_type=$(dig "$sub_domain.$domain" | awk '/IN\sA/ {print $4}')

    if [ -n "$record_type" ]; then
        destination=$(dig "$sub_domain.$domain" +short)
        echo "The subdomain $sub_domain is a $record_type record and points to $destination"
    else
        echo "No information found for the subdomain $sub_domain"
    fi
}

# Function to display information about default subdomains
display_default_subdomains_info() {
    domain="$1"
    sub_domains=("www" "lb-01" "web-01" "web-02")

    for sub_domain in "${sub_domains[@]}"; do
        display_subdomain_info "$sub_domain" "$domain"
    done
}

# Main function
main() {
    # Check if domain argument is provided
    if [ $# -lt 1 ]; then
        echo "Usage: $0 <domain> [<subdomain>]"
        exit 1
    fi

    domain="$1"
    sub_domain="$2"

    # If no subdomain provided, display information for default subdomains
    if [ -z "$sub_domain" ]; then
        display_default_subdomains_info "$domain"
    else
        display_subdomain_info "$sub_domain" "$domain"
    fi
}

# Execute main function with provided arguments
main "$@"

